basic app skeleton
corda/ui-starter-templates pull request #1
Opened 2022-08-24 09:42 UTC by zhengmar3

- Basic app setup with Vite.js, MUI, react-query, react-router-dom and mantine-hooks.
- Added very basic responsive header+navbar+main layout.

Very basic, but want to get some feedback on the overall project structure hence the PR.

2022-08-24 11:51 UTC, yarivus reviewed
@conor-r3 please review in detail ;)

2022-08-25 10:30 UTC, yarivus requested changes

2022-08-25 10:30 UTC, yarivus commented on mui-template-app/src/components/AppRoutes/AppRoutes.tsx
> +          <Route path="holygrail" element={<HolyGrailLayout />} />
fix indent

2022-08-25 10:30 UTC, yarivus commented on mui-template-app/src/components/SidbarLayout/SidbarLayout.tsx
> +function SidbarLayout() {
Sidbar => Sidebar

2022-08-25 13:20 UTC, zhengmar3 commented on mui-template-app/src/components/SidbarLayout/SidbarLayout.tsx
> +function SidbarLayout() {
Oh fixed

2022-08-25 13:22 UTC, zhengmar3 commented on mui-template-app/src/components/AppRoutes/AppRoutes.tsx
> +          <Route path="holygrail" element={<HolyGrailLayout />} />
I think this is in correct indentation.

_<Route path="holygrail" element={<HolyGrailLayout />} />_  is actually a child node of _<Route path="layout" element={<Layout />}>_

Hence the indentation.

Also, I have visual studio prettier plugin setup globally automatically. So the indentation should done automatically.

2022-08-25 19:39 UTC, yarivus reviewed
LGTM

2022-08-26 07:41 UTC, ellitrym1 commented on mui-template-app/src/components/AppRoutes/AppRoutes.tsx
> +          <Route path="holygrail" element={<HolyGrailLayout />} />
am i correct in assuming that the actual path for holygrail would be "/layout/holygrail" hence the indentation?

2022-09-01 13:10 UTC, merged

2022-09-01 20:32 UTC, yarivus reviewed
@conor-r3 please review this.
@zhengmar3 when can we see a demo ?

2022-09-02 08:35 UTC, zhengmar3 commented
@yarivus 

This is just a first PR for this professional service starter-template project.
No deployment is setup for this yet. But since it's pure front-end project. It's super easy to run the code locally.

If you want to see how it looks in browser, just git clone the code and:

``cd mui-template-app``
``npm install``
``npm run dev``

Otherwise, I will try to demo this work-in-progress project through all the front-end show and tell meeting.

2022-09-02 17:25 UTC, yarivus commented
@zhengmar3 thanks 😉
I've tried it out but obviously there's not much yet ...
I'll try in the next PRs when it has more stuff.
I do encourage to hold a quick demo and seek feedback in the next FE show & tell.

2022-09-06 12:35 UTC, conor-r3 commented on mui-template-app/src/components/Layout/Layout.tsx
> +function Layout() {
This is a good idea!